//
//  Constants.swift
//  BlaBlaCarClone
//
//  Created by Saheem Hussain on 10/05/23.
//

import Foundation

struct AppConstants {
    
    struct ApiUrls {
        static let baseUrl = "https://b16b-112-196-113-2.ngrok-free.app"
        static let users = "/users"
        static let logInEndPoint = "/users/sign_in"
        static let checkEmailEndPoint = "/email_check?email="
        static let sendOTP = "/phone"
        static let verifyPhone = "/verify"
        static let search = "/search"
        static let addImage = "/user_images"
        static let vehicles = "/vehicles"
        static let updatePassword = "/update_password"
        static let signOut = "/users/sign_out"
    }
    
    struct ApiKeys {
        static let image = "image"
    }
    
    struct AppHeadings {
        static let welcomeMssg = "Welcome to Carpool"
        static let yourRideChoice = "Your ride. Your choice."
        static let getStarted = "Let's get started"
        static let whatsYourName = "What's your name?"
        static let whatsYourDob = "What's your date of birth?"
        static let whatsYourgender = "How would you like to be addressed?"
        static let finishSignUp = "Finish signing up"
        static let enterPhone = "Please enter your Phone Number."
        static let selectDate = "When are you going?"
        static let rideAtLowPrice = "Your Pick of rides at low prices"
        static let noOfSeats = "Number of seats to book"
        static let filter = "Filter"
        static let sortBy = "Sort by"
        static let depTime = "Departure Time"
        static let amenities = "Amenities"
        static let rideDetails = "Ride Details"
        static let tripInfo = "Trip info"
        static let ridePreferences = "Ride Preferences"
        static let confirmRide = "Confirm Ride"
        static let profile = "Profile"
        static let personalDetails = "Personal Details"
        static let enterEmail = "Please enter the email you signed up with."
        static let enterOTP = "Please enter the OTP sent to your phone number"
        static let editProfilePic = "Don't wear sunglasses, look straight ahead and make sure you're alone."
        static let vehicleInfo = "Vehicle Info"
        static let editVehicle = "Edit Vehicle"
        
    }
    
    struct AppStrings {
        
        static let email = "Email"
        static let password = "Password"
        static let confirmPassword = "Confirm Password"
        static let alreadyMember = "Already a member?"
        static let notMember = "Not a member yet?"
        static let firstName = "First Name"
        static let lastName = "Last Name"
        static let step = "Step"
        static let of = "of"
        static let gender = "Gender"
        static let countryRegion = "IN"
        static let phoneNumber = "Phone Number"
        static let infoMssg = "Password must contain at least one number, one uppercase, "
        static let infoMssg2 = "one lowercase letter, one special character, and 8 or more characters."
        static let emailMessage = "Please enter valid email"
        static let weakPassword = "Weak Password"
        static let strongPassword = "Strong Password"
        static let confirmMssg = "Password doesn't match"
        static let login = "Login"
        static let male = "Mr."
        static let female = "Ms./Mrs."
        static let notSay = "I'd rather not say"
        static let phonePrompt = "Phone Number must be of 10 digits"
        static let phoneInt = "Phone Number consists of only digits."
        static let leavingFrom = "Leaving from"
        static let goingTo = "Going to"
        static let today = "Today"
        static let searchLoc = "Search Location"
        static let earlyDep = "Earliest Departure"
        static let lowPrice = "Lowest Price"
        static let closeDep = "Close to departure point"
        static let closArr = "Close to arrival point"
        static let shortRide = "Shortest ride"
        static let before6 = "Before 06:00"
        static let after6 = "06:00 - 12:00"
        static let after12 = "12:01 - 18:00"
        static let after6pm = "After 18:00"
        static let verifyprofile = "Verified Profile"
        static let max2 = "Max. 2 in the back"
        static let insBook = "Instant Booking"
        static let smokeAllow = "Smoking allowed"
        static let petsAllow = "Pets allowed"
        static let passenger = "passenger"
        static let seatsLeft = "Seats left"
        static let pricePerSeat = "Price for one seat"
        static let payVia = "Pay via wallet, card or cash"
        static let totalAmount = "Total amount"
        static let bookedSeats = "Booked Seats"
        static let bookedRideMessage = "Booked! Enjoy your ride"
        static let goToMyRides = "Go to \"My Rides\" section for details of your ride and more options"
        static let ratings = "Ratings"
        static let deleteAccount = "Delete Account"
        static let changePassword = "Change Password"
        static let aboutYou = "About You"
        static let vehicles = "Vehicles"
        static let verifyYourProfile = "Verify your Profile"
        static let memberSince = "Member Since"
        static let dateOfBirth = "Date of Birth"
        static let bio = "Bio"
        static let country = "Country"
        static let licensePlate = "License plate number"
        static let brand = "Vehicle brand"
        static let vehColor = "Vehicle colour"
        static let vehName = "Vehicle name"
        static let vehType = "Vehicle Type"
        static let vehModel = "Vehicle model year"
        static let ridePublishedMssg = "Your ride is online! Passengers can now book and travel with you!"
        static let rideCreated = "Your ride is created!"
        static let addAboutRide = "Got anything to add about the ride? Write it here."
        static let forExample = """
Eg; Flexible about when and where to meet? Got limited space in the boat?Need passengers to be punctual? etc.
"""
        static let deleteAlert = "Do you want to delete the vehicle?"
        static let currentPassword = "Current Password"
        static let newPassword = "New Password"
        static let dateAndTime = "Date and time of departure"
        static let selectVehicle = "Select a vehicle"
        static let priceSeat = "Price per seat"
        static let availableSeats = "Available Seats"
        static let rs = "Rs."
    }
    
    // MARK: - Button Labels
    struct ButtonLabels {
        
        static let contnue = "Continue"
        static let next = "Next"
        static let signUp = "Sign up"
        static let logIn = "Log in"
        static let search = "Search"
        static let done = "Done"
        static let currLoc = "Use my current location"
        static let filter = "Filter"
        static let clearAll = "Clear All"
        static let publish = "Publish"
        static let myRides = "My Rides"
        static let inbox = "Inbox"
        static let profile = "Profile"
        static let report = "Report ride"
        static let contact = "Contact"
        static let confirmRide = "Confirm Ride"
        static let ok = "OK"
        static let editProfile = "Edit personal details"
        static let editprofilePic = "Edit profile picture"
        static let logOut = "Log out"
        static let addBio = "Add a mini bio"
        static let addMyPreferences = "Add my preferences"
        static let addVehicle = "Add vehicle"
        static let confirmMyEmail = "Confirm email"
        static let confirmMyPhone = "Confirm phone"
        static let save = "Save"
        static let veify = "Verify"
        static let forgotPassword = "Forgot Password"
        static let submit = "Submit"
        static let editPhoto = "Edit Photo"
        static let addPhoto = "Add Photo"
        static let editVehicle = "Edit Vehicle"
        static let deleteVehicle = "Delete Vehicle"
        static let cancel = "Cancel"
        static let changePassword = "Change Password"
        static let publishRide = "Publish Ride"
        static let proceed = "Proceed"
        
    }
    
    // MARK: - App Images
    struct AppImages {
        
        static let carpool = "Carpool"
        static let eyeSlash = "eye.slash"
        static let eye = "eye"
        static let largeCircle = "largecircle.fill.circle"
        static let calendar = "calendar"
        static let person = "person"
        static let multiply = "multiply"
        static let plus = "plus.circle"
        static let minus = "minus.circle"
        static let star = "star.fill"
        static let bolt = "bolt"
        static let walkingFigure = "figure.walk.circle.fill"
        static let arrow = "arrow.right"
        static let chevronleft = "chevron.left"
        static let chevronRight = "chevron.right"
        static let paw = "pawprint"
        static let max2 = "person.2"
        static let smoke = "Smoke"
        static let noSmoke = "noSmoke"
        static let verifyProfile = "checkmark.shield.fill"
        static let clock = "clock"
        static let hourGlass = "hourglass"
        static let coins = "coins"
        static let circle = "circle"
        static let fillCircle = "circle.inset.filled"
        static let upDownArrow = "arrow.up.arrow.down.circle"
        static let magnifyingGlass = "magnifyingglass"
        static let publish = "plus.circle"
        static let message = "ellipsis.message"
        static let profile = "person.crop.circle"
        static let car = "car"
        static let distance = "point.topleft.down.curvedto.point.filled.bottomright.up"
        static let rideBook = "RideBook"
        static let checkmarkCircle = "checkmark.circle"
        static let personCircle = "person.circle.fill"
        static let chevronDown = "chevron.down"
    }

}
